### ISSUE TITLE
Improve the readability of the repo name?

### ISSUE THREAD

**Issue by oeway** [bioimage-io/pytorch-bioimage-io#1]
Should we rename `pytorchbioimageio` to improve the readability? ( e.g.: `pytorch-bioimage-io` etc.)

**Comment by constantinpape** [comment]
Just talked about this with @FynnBe, also for the `pythonbioimageio`.
I don't have strong feelings about this, so if we rather want
`python-bioimage-io` and `pytorch-bioimage-io`, I would be fine with renaming it.

**Comment by FynnBe** [comment]
renaming is fine for me, too...

**Comment by constantinpape** [comment]
Done for this repo, @FynnBe will rename it for the other one later.
